In [1]:
import sys
sys.path.append('..')  # pour importer portfolio_analytics depuis la racine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import portfolio_analytics as erk
%load_ext autoreload
%autoreload 2

In [7]:
data = pd.read_csv(
    "../data/Portfolios_Formed_on_ME_monthly_EW.csv",
    header=0,
    index_col=0,
    na_values=-99.99
)

data.index = pd.to_datetime(data.index, format="%Y%m").to_period("M")

In [ ]:
rets = data[["Lo 20", "Hi 20"]]

         Lo 20  Hi 20
1926-07  -0.57   3.33
1926-08   3.84   2.33
1926-09  -0.48  -0.09
1926-10  -3.29  -2.95
1926-11  -0.55   3.16
...        ...    ...
2018-08   3.09   2.49
2018-09  -2.04   0.19
2018-10 -10.52  -7.41
2018-11  -2.78   2.49
2018-12 -14.77  -9.21

[1110 rows x 2 columns]

In [52]:
rets = rets / 100
n_months = rets.shape[0]

annualized_rets = (1 + rets).prod() ** (12 / n_months) - 1
annualized_rets

Lo 20    0.151977
Hi 20    0.098490
dtype: float64

In [ ]:
volatility = rets.std(ddof=0) * np.sqrt(12)
volatility

Lo 20    0.003365
Hi 20    0.001950
dtype: float64

In [54]:
rets_1999_2015 = rets["1999":"2015"]
annualized_rets_1999_2015 = (1 + rets_1999_2015).prod() ** (12 / rets_1999_2015.shape[0]) - 1
annualized_rets_1999_2015

Lo 20    0.114426
Hi 20    0.062865
dtype: float64

In [ ]:
volatility_1999_2015 = rets_1999_2015.std(ddof=0) * np.sqrt(12)
volatility_1999_2015

Lo 20    0.228333
Hi 20    0.172289
dtype: float64

In [82]:
drawdown_1999_2015 = erk.drawdown(rets_1999_2015["Lo 20"])
print(drawdown_1999_2015.min())
drawdown_1999_2015.idxmin()

Wealth           1034.189842
Previous Peak    1111.400000
Drawdown           -0.624809
dtype: float64

Wealth           1999-03
Previous Peak    1999-01
Drawdown         2009-02
dtype: period[M]

In [83]:

drawdown_1999_2015_hi20 = erk.drawdown(rets_1999_2015["Hi 20"])
print(drawdown_1999_2015_hi20.min())
drawdown_1999_2015_hi20.idxmin()

Wealth            721.706638
Previous Peak    1015.300000
Drawdown           -0.552735
dtype: float64

Wealth           2002-09
Previous Peak    1999-01
Drawdown         2009-02
dtype: period[M]

In [66]:
rets_1999_2015

          Lo 20   Hi 20
1999-01  0.1114  0.0153
1999-02 -0.0399 -0.0172
1999-03 -0.0308  0.0368
1999-04  0.0824  0.0679
1999-05  0.0435 -0.0048
...         ...     ...
2015-08 -0.0347 -0.0559
2015-09 -0.0610 -0.0333
2015-10  0.0385  0.0710
2015-11  0.0165  0.0015
2015-12 -0.0500 -0.0229

[204 rows x 2 columns]

In [76]:
hfi = erk.get_hfi_returns()
hfi_2009_2018 = hfi["2009":"2018"]
semideviation_hfi_2009_2018 = erk.semideviation(hfi_2009_2018)
semideviation_hfi_2009_2018.sort_values()

c:\Users\user\Downloads\Simultation\edhec_risk_kit.py:39: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  hfi = pd.read_csv(

Fixed Income Arbitrage    0.003321
Merger Arbitrage          0.003611
Global Macro              0.005075
Equity Market Neutral     0.005186
Relative Value            0.005711
Convertible Arbitrage     0.006681
Funds Of Funds            0.007948
Distressed Securities     0.009498
Event Driven              0.010135
CTA Global                0.010996
Long/Short Equity         0.012139
Emerging Markets          0.015276
Short Selling             0.021240
dtype: float64

In [78]:
erk.skewness(hfi_2009_2018).sort_values()

Equity Market Neutral    -0.896327
Funds Of Funds           -0.646908
Merger Arbitrage         -0.551065
Event Driven             -0.488821
Long/Short Equity        -0.463703
Distressed Securities    -0.254944
Emerging Markets          0.033123
CTA Global                0.052062
Relative Value            0.159953
Global Macro              0.348184
Short Selling             0.456518
Fixed Income Arbitrage    1.121453
Convertible Arbitrage     1.305911
dtype: float64

In [79]:
erk.kurtosis(hfi_2009_2018).sort_values()

CTA Global                2.591087
Merger Arbitrage          2.715238
Global Macro              3.164362
Distressed Securities     3.319725
Event Driven              3.620617
Funds Of Funds            3.816132
Long/Short Equity         4.115713
Short Selling             4.175832
Emerging Markets          4.401636
Relative Value            4.512482
Equity Market Neutral     5.071677
Fixed Income Arbitrage    6.406941
Convertible Arbitrage     6.775731
dtype: float64